config/routes.rb
Rails.application.routes.draw do
  resources :matches do
    resources :comments, only: [:create]
    get '/page/:page', action: :index, on: :collection
  end

  root "root#main"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :match
end

app/models/match.rb
class Match < ApplicationRecord
  paginates_per 5

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @match = Match.find(params[:match_id])
    @comment = @match.comments.build(comment_params)
    @comment.save
    redirect_to @comment.match
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:title, :author, :content, :match_id)
    end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[ show edit update destroy ]

  # GET /matches or /matches.json
  def index
    if params[:search].present?
      @matches = Match.where("first_team LIKE ? OR secod_team LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%").page(params[:page])
    else
      @matches = Match.page(params[:page])
    end
  end

  # GET /matches/1 or /matches/1.json
  def show
    @comment = @match.comments.new
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches or /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to match_url(@match), notice: "Match was successfully created." }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1 or /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to match_url(@match), notice: "Match was successfully updated." }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1 or /matches/1.json
  def destroy
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url, notice: "Match was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_params
      params.require(:match).permit(:first_team, :secod_team, :first_team_score, :second_team_score)
    end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def main
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Title:</strong>
    <%= comment.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= comment.author %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= comment.content %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Wyniki Sportowe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
  <div class="container-fluid" style="background: #5b4282;">
      <!-- Nagłówek strony z logo -->
      <div class="row">
          <div class="col-12">
              <header class="d-flex justify-content-center align-items-center py-3">
                  <%# <img src="link_do_loga.png" alt="Logo" class="mr-2"> %>
                  <h1 style="color: white;">Wyniki Sportowe</h1>
              </header>
          </div>
      </div>
    </div>
    <!-- Menu boczne i główna zawartość -->
  <div id="wrapper">
  <!-- Sidebar -->
    <div id="sidebar-wrapper">
      <ul class="sidebar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Matches", matches_path%></li>
        <li><a href="#">Teams</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
    </div>
  
  <!-- Page Content -->
    <div id="page-content-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <a class="btn" id="menu-toggle"><img src='/menu.png', width="50", height="50"></a>
            <div class="text-center"> 
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    <!-- Podłączenie Bootstrap JS i zależności -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

<script>
$(document).ready(function(){
  console.log("dupa")
  $("#menu-toggle").click(function(e){
    console.log("dupa")
    e.preventDefault();
    $("#wrapper").toggleClass("menuDisplayed");
  });
});
</script>

app/views/matches/_form.html.erb
<%= form_with(model: match) do |form| %>
  <% if match.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div>
      <%= "_______First team ___________First team score_________Second team score________Second team_____" %>
      


    </div>

    <div>
    <%= form.text_field :first_team %>
    <%= form.number_field :first_team_score %>
    vs.
    <%= form.number_field :second_team_score %>
    <%= form.text_field :secod_team %>
    </div>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/matches/_match.html.erb
<%= link_to 'Back', matches_path(), class: 'btn btn-xs btn-primary my-1' %>
<%= link_to 'Edit',
            edit_match_path(match), :class => 'btn btn-default btn-xs' %>
<%= link_to 'Destroy', match_path(match),
            :data => { method: :delete, :confirm =>  'Are you sure?' },
            :class => 'btn btn-xs btn-danger' %>

<div id="<%= dom_id match %>">
  <p>
    <h1>Match</h1> </br></br>
    <strong><%= match.first_team %></strong>
    <%= match.first_team_score %>
    :
    <%= match.second_team_score %>
    <strong><%= match.secod_team %></strong>
  </p>

  <h1>Match</h1> </br></br>

  <div class="container-fluid table-bordered">
    <div class="row">                                           
          <!-- Need to add theme, buttons -->                       
        <div class="col-xs-12">
         Tu kiedyś powstanie przedstwaianie wszystkich wydarzeń z meczu na rzywo 
        </div>          
    </div>
</div></br></br>

<div align="left">
  <h1>Comments</h1> </br></br>
  <% if @match.comments.any? %>
    <h3>Komentarze:</h3>
    <% @match.comments.each do |comment| %>
      <% if comment.author? %>
      <p><h2><%= comment.author %></h2></p>
      <p> <h3><%= comment.title %></h3> </br><%= comment.content %></p>
      --------------------------------------------------
      <% end %>
    <% end %>
  <% end %>




<h1>Add new comment</h1>
<%= form_with(model: [ @match, Comment.new ]) do |form| %>
<div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
</div>
<div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>
  <div>
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render "form", match: @match %>

<br>

<div>
  <%= link_to "Show this match", @match %> |
  <%= link_to "Back to matches", matches_path %>
</div>

app/views/matches/index.html.erb
<p style="color: green"><%= notice %></p>
<div align="left">
<%= link_to "New match", new_match_path , class: 'btn btn-xs btn-primary my-1' %>
</div>
<div align="right">
<%= form_tag matches_path, method: :get do %>
  <%= text_field_tag :search, params[:search], placeholder: "Szukaj drużyny" %>
  <%= submit_tag "Szukaj", name: nil %>
<% end %>
</div>
<%= paginate @matches %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">First team</th>
      <th scope="col">First team score</th>
      <th scope="col">Second team score</th>
      <th scope="col">Second team</th>
      <th scope="col">Created at</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @matches.each do |match| %>
        <tr>
          <td><%= match.id %></td>
          <td><%= match.first_team %></td>
          <td><%= match.first_team_score %></td>
          <td><%= match.second_team_score %></td>
          <td><%= match.secod_team %></td>
          <td><%= match.created_at %></td>
          <td>
          <%= link_to 'Show', match_path(match), class: 'btn btn-xs btn-primary my-1' %>
          <%= link_to 'Edit',
                      edit_match_path(match), :class => 'btn btn-default btn-xs' %>
          <%= link_to 'Destroy',
                      match_path(match),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
        </tr>
      </a>
    <%end%>
  </tbody>
</table>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render "form", match: @match %>

<br>

<div>
  <%= link_to "Back to matches", matches_path %>
</div>

app/views/matches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @match %>

app/views/root/main.html.erb
<h1> Lorem Ipsum </h1>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas in sapien a libero tempus molestie et sed mi. 
Aenean ullamcorper felis sit amet laoreet sollicitudin. Nunc mattis quis risus ac dictum. Vivamus non venenatis lectus. 
Praesent velit felis, ultricies eget nulla in, viverra efficitur lectus. Morbi efficitur neque in ipsum aliquam suscipit.
 Fusce aliquet, ligula at malesuada commodo, sapien eros faucibus ipsum, iaculis rutrum dolor urna vel diam. Ut nec nulla
  vulputate, sollicitudin ligula mattis, sollicitudin mi. Sed vel consequat ligula, ac pretium risus. Sed et mi eget leo 
  ultrices imperdiet quis ut ex. Aliquam a metus mauris. Aliquam rutrum nisl viverra dignissim egestas. Nunc ex eros,
   accumsan nec arcu ac, tincidunt molestie mauris.
</p>